baseURL = "https://blog.serplux.com/"
languageCode = "en-us"
title = "Serplux"

# Enable for syntax highlighting
pygmentsClass = true
pygmentsCodefences = true
pygmentsStyle = "friendly"

pagination.pagerSize = 9

[taxonomies]
  author = "author"
  tag = "tags"
  

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.7

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML","RSS"]
  taxonomy = ["HTML", "RSS"]


[params]
  linkedin = "https://www.linkedin.com/company/serplux/"
  github = "https://github.com/serplux"
  ogimage = "https://serplux.com/frontend/images/hero-og.png"
  tagline = "World's #1 AI Agents for Instant Marketing Solutions"
  blogtitle = "Serplux"
  description = "Discover Serplux, the world's #1 AI-powered marketing assistant. Instantly tackle any marketing task without the need for endless searches, blogs, or prompts. Let our AI agents handle everything in secondsâ€”efficient, fast, and beyond ChatGPT."
  twitter = "@SerpluxAI"

  [markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params.shareButtons]
  size = "small"
  networks = ["facebook", "twitter"]

enableRobotsTXT = true